### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by jeremymeyers** [kavika13/jumpmanzero#30]
Will binaries be made available? Actually I'm not sure if the project is runnable overall?

**Comment by merlynmg** [comment]
The game has been runnable for a long time.
If you're on Windows check the Releases tab, where binaries usually hang out on github :)
https://github.com/kavika13/jumpmanzero/releases

**Comment by kavika13** [comment]
The game has been runnable for a long time.
https://github.com/kavika13/jumpmanzero/releases
This is an old binary, with the old version of the source code, but it plays the entire game just fine and it should work on Windows XP or above.

The code in the tree is quite a bit newer, and still working and runnable once compiled. The music sounds much nicer now and it supports higher resolution. It also uses Lua instead of the proprietary compiled scripting language it used to use. I can put out some more recent binaries if you're interested. Which OS are you on?

I also can update the compile instructions. It works on MacOS and Linux now, when compiled correctly. I haven't been updating those because it's been more fun to just make progress on the project itself.

**Comment by kavika13** [comment]
Hmm. Cutting a release wasn't such a big deal, I just decided to go ahead and do it.
Let me know if it works for you or if you encounter any problems!
If you need it for OSX or Linux instead, let me know :)

**Comment by jeremymeyers** [comment]
(running on win10. will let you know how it goes)...sorry just saw this pop up
